# Generated by Django 4.0.4 on 2022-04-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('doctor', 'Is a doctor'), ('nurse', 'Is a nurse'), ('medical professional', 'Is a nurse or doctor'), ('billing', 'Is at the billing desk'))},
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
