# Generated by Django 4.0.4 on 2022-04-11 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('doctor', 'Is a doctor'), ('nurse', 'Is a nurse'), ('medical professional', 'Is a nurse or doctor'), ('billing', 'Is at the billing desk'), ('registration', 'is a registrar desk'))},
        ),
    ]
