# Generated by Django 4.0.4 on 2022-04-11 22:22

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_patient_options_alter_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='medicine',
            field=models.CharField(choices=[('A', 'Insulin'), ('B', 'Candesartan'), ('C', 'Dexamethasone'), ('D', 'Azithromycin'), ('E', 'Fluticasone'), ('F', 'Alteplase'), ('G', 'Aspirin')], default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='cost',
            field=models.FloatField(help_text='Weight in kg: ', validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
