# Generated by Django 4.0.4 on 2022-04-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_patient_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='medicine',
            field=models.CharField(choices=[('A', 'Insulin'), ('B', 'Candesartan'), ('C', 'Dexamethasone'), ('D', 'Azithromycin'), ('E', 'Fluticasone'), ('F', 'Alteplase'), ('G', 'Aspirin')], max_length=1, null=True),
        ),
    ]
