# Generated by Django 4.0.4 on 2022-04-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_medication_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='medicine',
            field=models.CharField(choices=[('A', 'Insulin'), ('B', 'Candesartan'), ('C', 'Dexamethasone'), ('D', 'Azithromycin'), ('E', 'Fluticasone'), ('F', 'Alteplase'), ('G', 'Aspirin')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
