# Generated by Django 4.0.4 on 2022-04-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_patient_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bill_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
