# Generated by Django 4.0.4 on 2022-04-14 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_patient_bill_due_date_delete_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidvaccineshot',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='staff.patient'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CovidVaccineInfo',
        ),
    ]
