# Generated by Django 4.0.4 on 2022-04-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_covidvaccineshot_patient_delete_covidvaccineinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='insurance_provider',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='primary_doctor_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
